### ISSUE TITLE
brew out of date

### ISSUE THREAD

**Issue by 75lb** [acaudwell/Logstalgia#11]
on Mac, it's much quicker to `brew install` this tool than manually install all the deps required to build.. but it seems like the brew recipe is out of date - is it maintained by you? are you able to update it?

**Comment by acaudwell** [comment]
FYI the --HEAD option on brew will try and install the latest version of the source code directly from Github.

AFAIK anyone can submit updates to brew formulas as pull requests on their github page ;)
