### ISSUE TITLE
Compiling 1.0.8 on FreeBSD: error: unknown type name 'FILEWATCHER_IMPL'

### ISSUE THREAD

**Issue by ehaupt** [acaudwell/Logstalgia#22]
Compiling 1.0.8 on FreeBSD produces the following error:

```
src/FileWatcher/FileWatcher.cpp:43:15: error: unknown type name 'FILEWATCHER_IMPL'
                mImpl = new FILEWATCHER_IMPL();
                            ^
1 error generated.
gmake[1]: *** [Makefile:986: src/FileWatcher/logstalgia-FileWatcher.o] Error 1
```

**Comment by gonzalo-** [comment]
Same on OpenBSD.

**Comment by acaudwell** [comment]
Can you modify this line FileWatcher/FileWatcherImpl.h and see if it compiles?

#elif defined(__APPLE_CC__) || defined(BSD)

It looks like that is the intention of that line, though maybe it is looking for the wrong variable name. Maybe it should look for __unix__?

**Comment by gonzalo-** [comment]
Thank you for your quick reply:

With:

#elif defined(APPLE_CC) || defined(__OpenBSD__)

or

#elif defined(APPLE_CC) || defined(__unix__)

I got this:

``atcher/FileWatcher.cpp
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
In file included from src/FileWatcher/FileWatcher.cpp:30:
src/FileWatcher/FileWatcherOSX.h:79:19: error: field has incomplete type 'struct timespec'
                struct timespec mTimeOut;
                                ^
src/FileWatcher/FileWatcherOSX.h:79:10: note: forward declaration of 'FW::timespec'
                struct timespec mTimeOut;
                       ^
src/FileWatcher/FileWatcher.cpp:43:11: error: assigning to 'FW::FileWatcherImpl *' from incompatible type 'FW::FileWatcherOSX *'
                mImpl = new FILEWATCHER_IMPL();
                        ^~~~~~~~~~~~~~~~~~~~~~
1 warning and 2 errors generated.
``

**Comment by acaudwell** [comment]
Try adding `#include <time.h>`

**Comment by acaudwell** [comment]
may also need to remove the 'struct' before 'struct timespec'

**Comment by gonzalo-** [comment]
``
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
src/FileWatcher/FileWatcherOSX.cpp:99:43: error: use of undeclared identifier 'O_EVTONLY'
                        int fd = open(name.c_str(), O_RDONLY | O_EVTONLY);
                                                               ^
src/FileWatcher/FileWatcherOSX.cpp:228:47: error: use of undeclared identifier 'O_EVTONLY'
                        int fd = open(mDirName.c_str(), O_RDONLY | O_EVTONLY);
                                                                   ^
1 warning and 2 errors generated.
*** Error 1 in /usr/obj/ports/logstalgia-1.0.8/logstalgia-1.0.8 (Makefile:1001 'src/FileWatcher/logstalgia-FileWatcherOSX.o')
``

**Comment by acaudwell** [comment]
Can you try not passing O_EVTONLY? I don't think it is needed. Apparently doesn't exist on BSD.

**Comment by gonzalo-** [comment]
Bingo!

Seems to be working now.

Are you gonna commit this changes?

**Comment by acaudwell** [comment]
I've pushed a fix incorporating these changes, can you check if it works?

Do you know if https://github.com/acaudwell/Logstalgia/pull/23 is also needed?

**Comment by gonzalo-** [comment]
Well that change is just for FreeBSD, my test are on OpenBSD, so I think we don't need it so far.

**Comment by ehaupt** [comment]
I just tried 32067aa on FreeBSD and now I get:
```

c++ -DPACKAGE_NAME=\"Logstalgia\" -DPACKAGE_TARNAME=\"logstalgia\" -DPACKAGE_VERSION=\"1.0.8\" -DPACKAGE_STRING=\"Logstalgia\ 1.0.8\" -DPACKAGE_BUGREPORT=\"acaudwell@gmail.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"logstalgia\" -DVERSION=\"1.0.8\" -DHAVE_PTHREAD=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_GL_GL_H=1 -DHAVE_GL_GLU_H=1 -DHAVE_IMG_LOADPNG_RW=1 -DHAVE_IMG_LOADJPG_RW=1 -DHAVE_BOOST=/\*\*/ -I.  -Isrc/FileWatcher -DSDLAPP_RESOURCE_DIR=\"/usr/local/share/logstalgia\"  -isystem /usr/local/include -I/usr/local/include -D_THREAD_SAFE -pthread -I/usr/local/include -D_THREAD_SAFE -pthread -I/usr/local/include/freetype2  -I/usr/local/include  -I/usr/local/include -I/usr/local/include/libdrm -D_THREAD_SAFE -pthread  -I/usr/local/include/SDL2 -I/usr/local/include -D_REENTRANT -D_THREAD_SAFE  -I/usr/local/include/libpng16  -I/usr/local/include -std=gnu++0x -Wall -Wno-sign-compare -Wno-reorder -Wno-unused-variable -O2 -pipe -fstack-protector -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include -I/usr/local/include -D_THREAD_SAFE -pthread -I/usr/local/include -D_THREAD_SAFE -pthread -MT src/logstalgia-tests.o -MD -MP -MF src/.deps/logstalgia-tests.Tpo -c -o src/logstalgia-tests.o `test -f 'src/tests.cpp' || echo './'`src/tests.cpp
mv -f src/.deps/logstalgia-paddle.Tpo src/.deps/logstalgia-paddle.Po
mv -f src/.deps/logstalgia-requestball.Tpo src/.deps/logstalgia-requestball.Po
mv -f src/.deps/logstalgia-slider.Tpo src/.deps/logstalgia-slider.Po
mv -f src/.deps/logstalgia-summarizer.Tpo src/.deps/logstalgia-summarizer.Po
mv -f src/.deps/logstalgia-textarea.Tpo src/.deps/logstalgia-textarea.Po
mv -f src/.deps/logstalgia-tests.Tpo src/.deps/logstalgia-tests.Po
mv -f src/.deps/logstalgia-settings.Tpo src/.deps/logstalgia-settings.Po
src/FileWatcher/FileWatcherOSX.cpp:232:47: error: use of undeclared identifier 'O_EVTONLY'
                        int fd = open(mDirName.c_str(), O_RDONLY | O_EVTONLY);
                                                                   ^
1 error generated.
gmake[1]: *** [Makefile:1000: src/FileWatcher/logstalgia-FileWatcherOSX.o] Error 1
gmake[1]: Leaving directory '/usr/ports/sysutils/logstalgia/work/Logstalgia-32067aa'
```
Without the patch from https://github.com/acaudwell/Logstalgia/pull/23 I get:

```
c++ -DPACKAGE_NAME=\"Logstalgia\" -DPACKAGE_TARNAME=\"logstalgia\" -DPACKAGE_VERSION=\"1.0.8\" -DPACKAGE_STRING=\"Logstalgia\ 1.0.8\" -DPACKAGE_BUGREPORT=\"acaudwell@gmail.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"logstalgia\" -DVERSION=\"1.0.8\" -DHAVE_PTHREAD=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_GL_GL_H=1 -DHAVE_GL_GLU_H=1 -DHAVE_IMG_LOADPNG_RW=1 -DHAVE_IMG_LOADJPG_RW=1 -DHAVE_BOOST=/\*\*/ -I.  -Isrc/FileWatcher -DSDLAPP_RESOURCE_DIR=\"/usr/local/share/logstalgia\"  -isystem /usr/local/include -I/usr/local/include -D_THREAD_SAFE -pthread -I/usr/local/include -D_THREAD_SAFE -pthread -I/usr/local/include/freetype2  -I/usr/local/include  -I/usr/local/include -I/usr/local/include/libdrm -D_THREAD_SAFE -pthread  -I/usr/local/include/SDL2 -I/usr/local/include -D_REENTRANT -D_THREAD_SAFE  -I/usr/local/include/libpng16  -I/usr/local/include -std=gnu++0x -Wall -Wno-sign-compare -Wno-reorder -Wno-unused-variable -O2 -pipe -fstack-protector -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include -I/usr/local/include -D_THREAD_SAFE -pthread -I/usr/local/include -D_THREAD_SAFE -pthread -MT src/logstalgia-tests.o -MD -MP -MF src/.deps/logstalgia-tests.Tpo -c -o src/logstalgia-tests.o `test -f 'src/tests.cpp' || echo './'`src/tests.cpp
mv -f src/.deps/logstalgia-summarizer.Tpo src/.deps/logstalgia-summarizer.Po
mv -f src/.deps/logstalgia-settings.Tpo src/.deps/logstalgia-settings.Po
mv -f src/.deps/logstalgia-textarea.Tpo src/.deps/logstalgia-textarea.Po
mv -f src/.deps/logstalgia-tests.Tpo src/.deps/logstalgia-tests.Po
src/FileWatcher/FileWatcherOSX.cpp:232:47: error: use of undeclared identifier 'O_EVTONLY'
                        int fd = open(mDirName.c_str(), O_RDONLY | O_EVTONLY);
                                                                   ^
1 error generated.
gmake[1]: *** [Makefile:1000: src/FileWatcher/logstalgia-FileWatcherOSX.o] Error 1
gmake[1]: *** Waiting for unfinished jobs....
In file included from src/ncsa.cpp:18:
In file included from src/ncsa.h:21:
src/logentry.h:46:5: error: unknown type name 'time_t'
    time_t timestamp;
    ^
1 error generated.
gmake[1]: *** [Makefile:1056: src/logstalgia-ncsa.o] Error 1
In file included from src/custom.cpp:1:
In file included from src/custom.h:21:
src/logentry.h:46:5: error: unknown type name 'time_t'
    time_t timestamp;
    ^
1 error generated.
gmake[1]: *** [Makefile:1070: src/logstalgia-custom.o] Error 1
In file included from src/logentry.cpp:18:
src/logentry.h:46:5: error: unknown type name 'time_t'
    time_t timestamp;
    ^
1 error generated.
gmake[1]: *** [Makefile:1084: src/logstalgia-logentry.o] Error 1
gmake[1]: Leaving directory '/usr/ports/sysutils/logstalgia/work/Logstalgia-32067aa'
```

**Comment by ehaupt** [comment]
The following patch will solve the above error:

```
--- src/FileWatcher/FileWatcherOSX.cpp.orig     2017-10-01 03:38:27 UTC
+++ src/FileWatcher/FileWatcherOSX.cpp
@@ -229,7 +229,11 @@ namespace FW
                void addAll()
                {
                        // add base dir
+#ifdef O_EVTONLY
                        int fd = open(mDirName.c_str(), O_RDONLY | O_EVTONLY);
+#else
+                       int fd = open(mDirName.c_str(), O_RDONLY );
+#endif
                        EV_SET(&mChangeList[0], fd, EVFILT_VNODE,
                                   EV_ADD | EV_ENABLE | EV_ONESHOT,
                                   NOTE_DELETE | NOTE_EXTEND | NOTE_WRITE | NOTE_ATTRIB,
```

**Comment by acaudwell** [comment]
Thanks. I missed the second O_EVTONLY. It's fixed now.

**Comment by gonzalo-** [comment]
Seems ok so far, are you gonna bump a new version?

**Comment by acaudwell** [comment]
I found another bug with the filewatcher so I'm going to fix that first.

**Comment by acaudwell** [comment]
Would be good if you could test the change detection is working (after pulling my latest changes):

Make a file test.conf:
```
[logstalgia]
detect-changes=true
path=data/example.log
title=Test
```
Run with: `./logstalgia --load-config test.conf`

While its running, edit test.conf to change the title and save and see if the title changes in Logstalgia.

**Comment by ehaupt** [comment]
793877e looks good on FreeBSD.

**Comment by acaudwell** [comment]
Thanks for checking.

I just tried it on OSX and there are a couple things wrong so it is probably the same issue. The events get sent to ConfigWatcher::handleFileAction but:
- the file path it returns is a full path including the directory so the filename comparison currently fails.
- it seems to generate some erroneous events so I will need to manually stat the file to see if it actually changed

**Comment by acaudwell** [comment]
I might abandon this approach and just periodically poll the config with stat...

**Comment by acaudwell** [comment]
https://github.com/acaudwell/Logstalgia/commit/ea6ed72d2bf05163b00e3d04c89756baad1f3091

**Comment by ehaupt** [comment]
ea6ed72 looks good. Here's the full poudriere build log https://critical.ch/people/logstalgia/logstalgia-1.0.8.log

**Comment by acaudwell** [comment]
Have made a 1.0.9 release. Thanks again.
