### ISSUE TITLE
2d2006b fails to build on FreeBSD

### ISSUE THREAD

**Issue by ehaupt** [acaudwell/Logstalgia#24]
2d2006b fails to build on FreeBSD. [Full build log](https://critical.ch/people/F73576B654-355C7783D8-7342D96D8D-136F241692/logstalgia-1.1.0.log).

**Comment by acaudwell** [comment]
It looks like for some reason you don't have the src/core submodule up todate as the FXFontManager::grab has a new 4 optional argument in both the tarball and the tagged version.

**Comment by ehaupt** [comment]
Ah that's it. Updating the core lib to the latest version solves the issue.
