### ISSUE TITLE
Cannot get --display-fields to have any affect

### ISSUE THREAD

**Issue by johnsq** [acaudwell/Logstalgia#28]
Hello,
Absolutely love this software, so well done.

However, I like the idea of having more info show when hovering over a request, but whatever I try has zero effect.

Tried with quotes..
ssh root@myserver "tail -f /var/log/access.log" | logstalgia --display-fields "path,hostname,response_size,response_code,method,protocol,timestamp,referrer,user_agent,vhost" --sync
 
Tried without quotes..
ssh root@myserver "tail -f /var/log/access.log" | logstalgia --display-fields path,hostname,response_size,response_code,method,protocol,timestamp,referrer,user_agent,vhost --sync

Tried fewer fields..
ssh root@myserver "tail -f /var/log/access.log" | logstalgia --display-fields path,user_agent --sync

Using logstalgia-1.1.0.

Whatever I set, hovering over a request only shows something like "001 /home/".
Hovering over an ip address on the left only ever shows something like "001 157.55.39-".

Please can you post a working example?

Thanks

**Comment by acaudwell** [comment]
This is controlling the fields displayed when you hover over the individual request balls while paused (space).

**Comment by johnsq** [comment]
Ah. I'll try that now. 

By the way.. this software has been of great use to us. We have it running all day in the office on a TV screen. I used to hate trawling through an access log and so would generally not bother, but with Logstalgia we can always glance up and see in realtime who is doing what on our website. From the first day we were seeing repeated hits to our admin logins pages and so were able to quickly block their IPs. 

10 out of 10 !!
