### ISSUE TITLE
PKG_CONFIG_PATH

### ISSUE THREAD

**Issue by Newyork311** [acaudwell/Logstalgia#31]
Can help me with this error, thanks

./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for X... libraries , headers
checking for a sed that does not truncate output... /bin/sed
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether we are using the Microsoft C compiler... no
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking for GL/gl.h... yes
checking for OpenGL/gl.h... no
checking for OpenGL library... -lGL
checking for GL/glu.h... yes
checking for OpenGL/glu.h... no
checking for OpenGL Utility library... -lGLU
checking for varargs GLU tesselator callback function type... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for FT2... yes
checking for PCRE... yes
checking for GLEW... yes
checking for SDL2... configure: error: Package requirements (sdl2 SDL2_image) were not met:

No package 'sdl2' found
No package 'SDL2_image' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SDL2_CFLAGS
and SDL2_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Its installed already
sdl2
SDL2_image

centos
CentOS release 6.10 (Final)

PKG CONFIG

/usr/lib64/pkgconfig
/usr/lib64/pkgconfig/com_err.pc
/usr/lib64/pkgconfig/fontutil.pc
/usr/lib64/pkgconfig/form.pc
/usr/lib64/pkgconfig/formw.pc
/usr/lib64/pkgconfig/gnome-python-desktop-2.0.pc
/usr/lib64/pkgconfig/gnome-python-extras-2.0.pc
/usr/lib64/pkgconfig/gnome-screensaver.pc
/usr/lib64/pkgconfig/libargon2.pc
/usr/lib64/pkgconfig/libcrypto.pc
/usr/lib64/pkgconfig/libedit.pc
/usr/lib64/pkgconfig/libpcre.pc
/usr/lib64/pkgconfig/libpcrecpp.pc
/usr/lib64/pkgconfig/libselinux.pc
/usr/lib64/pkgconfig/libsepol.pc
/usr/lib64/pkgconfig/libssl.pc
/usr/lib64/pkgconfig/libxml-2.0.pc
/usr/lib64/pkgconfig/menu.pc
/usr/lib64/pkgconfig/menuw.pc
/usr/lib64/pkgconfig/ncurses.pc
/usr/lib64/pkgconfig/ncursesw.pc
/usr/lib64/pkgconfig/netapi.pc
/usr/lib64/pkgconfig/notify-python.pc
/usr/lib64/pkgconfig/openssl.pc
/usr/lib64/pkgconfig/panel.pc
/usr/lib64/pkgconfig/panelw.pc
/usr/lib64/pkgconfig/tic.pc
/usr/lib64/pkgconfig/tinfo.pc
/usr/lib64/pkgconfig/zlib.pc
/usr/share/pkgconfig
/usr/share/doc/pkgconfig-0.23
/usr/share/doc/pkgconfig-0.23/AUTHORS
/usr/share/doc/pkgconfig-0.23/COPYING
/usr/share/doc/pkgconfig-0.23/NEWS
/usr/share/doc/pkgconfig-0.23/README
/usr/share/gtksourceview-2.0/language-specs/pkgconfig.lang
/usr/share/pkgconfig/gnome-default-applications.pc
/usr/share/pkgconfig/gnome-doc-utils.pc
/usr/share/pkgconfig/gnome-icon-theme.pc
/usr/share/pkgconfig/gnome-keybindings.pc
/usr/share/pkgconfig/shared-mime-info.pc
/usr/share/pkgconfig/usbutils.pc
/usr/share/pkgconfig/xml2po.pc
/var/lib/yum/yumdb/p/481188174c707a1a3cfa09696240917b7c3ef8b7-pkgconfig-0.23-9.1.el6-x86_64
/var/lib/yum/yumdb/p/481188174c707a1a3cfa09696240917b7c3ef8b7-pkgconfig-0.23-9.1.el6-x86_64/checksum_data
/var/lib/yum/yumdb/p/481188174c707a1a3cfa09696240917b7c3ef8b7-pkgconfig-0.23-9.1.el6-x86_64/checksum_type
/var/lib/yum/yumdb/p/481188174c707a1a3cfa09696240917b7c3ef8b7-pkgconfig-0.23-9.1.el6-x86_64/from_repo
/var/lib/yum/yumdb/p/481188174c707a1a3cfa09696240917b7c3ef8b7-pkgconfig-0.23-9.1.el6-x86_64/from_repo_revision
/var/lib/yum/yumdb/p/481188174c707a1a3cfa09696240917b7c3ef8b7-pkgconfig-0.23-9.1.el6-x86_64/from_repo_timestamp
/var/lib/yum/yumdb/p/481188174c707a1a3cfa09696240917b7c3ef8b7-pkgconfig-0.23-9.1.el6-x86_64/installed_by
/var/lib/yum/yumdb/p/481188174c707a1a3cfa09696240917b7c3ef8b7-pkgconfig-0.23-9.1.el6-x86_64/reason
/var/lib/yum/yumdb/p/481188174c707a1a3cfa09696240917b7c3ef8b7-pkgconfig-0.23-9.1.el6-x86_64/releasever

I try also

export PKG_CONFIG_PATH=/usr/bin/pkgconfig

nothing

**Comment by acaudwell** [comment]
Basically like the error says, it looks like it can't find the pkgconfig files for sdl2 and SDL2_image (think these will be called sdl2.pc and SDL2_image.pc). Make sure you've installed the developer version of the sdl2 and SDL2_image packages.

It looks like SDL2 dev package is called SDL2-devel on Centos.

**Comment by Newyork311** [comment]
> It looks like SDL2 dev package is called SDL2-devel on Centos.

Centos Says doesnt exist that package
